import { resolve } from 'node:path';

const root = resolve(import.meta.dir, '..');
const packageJson = await Bun.file(resolve(root, 'package.json')).json() as { version?: unknown };

if (typeof packageJson.version !== 'string' || !/^\d+\.\d+\.\d+$/.test(packageJson.version)) {
	throw new Error(`package.json version must use numeric X.Y.Z format: ${String(packageJson.version)}`);
}

const output = [
	'// Generated from package.json by scripts/sync-xcode-version.ts.',
	'// Do not edit this file directly.',
	`ARIA_CLIP_VERSION = ${packageJson.version}`,
	''
].join('\n');

await Bun.write(resolve(root, 'xcode/Aria Clip/Version.xcconfig'), output);
console.log(`Synced Xcode marketing version ${packageJson.version}`);
