import { resolve } from 'node:path';

const root = resolve(import.meta.dir, '..');
const packageJson = await Bun.file(resolve(root, 'package.json')).json() as { version?: unknown };

if (typeof packageJson.version !== 'string' || !/^\d+\.\d+\.\d+$/.test(packageJson.version)) {
	throw new Error(`package.json version must use numeric X.Y.Z format: ${String(packageJson.version)}`);
}

const output = [
	'// Generated from package.json by scripts/sync-xcode-version.ts.',
	'// Do not edit this file directly.',
	`ARIA_CLIP_VERSION = ${packageJson.version}`,
	''
].join('\n');

await Bun.write(resolve(root, 'xcode/Aria Clip/Version.xcconfig'), output);

const appScript = await Bun.build({
	entrypoints: [resolve(root, 'src/entrypoints/safari-app.ts')],
	format: 'iife',
	minify: false,
	target: 'browser',
});
if (!appScript.success || appScript.outputs.length !== 1) {
	throw new AggregateError(appScript.logs, 'Could not compile the Safari containing-app script.');
}
await Bun.write(
	resolve(root, 'xcode/Aria Clip/Shared (App)/Resources/Script.js'),
	appScript.outputs[0],
);
console.log(`Synced Xcode marketing version ${packageJson.version}`);
